branch-defaults:
  master:
    environment: locustio-dev
    group_suffix: null
global:
  application_name: locustio
  branch: null
  default_ec2_keyname: DINNEROUT
  default_platform: Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
